version: '2'

services:
  app:
    image: 'docker-device-postgres:latest'
    build:
      context: .
    container_name: device-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:9090/compose-postgres
      - SPRING_DATASOURCE_USERNAME=userMeakef
      - SPRING_DATASOURCE_PASSWORD=P@ssw0rd
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres